-- 僅對 P120 三張資料表啟用 RLS。

ALTER TABLE public."TblP120Transfer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP120File" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP120RateLimit" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."TblP120Transfer" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."TblP120File" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."TblP120RateLimit" FORCE ROW LEVEL SECURITY;
